_target_: src.models.ensemble_module.EnsembleLitModule
num_classes: 10
run_paths:
  - "ducholmes-vietnam-national-university-hanoi/MNIST-SOTA/gnvcb9cl"
  - "ducholmes-vietnam-national-university-hanoi/MNIST-SOTA/i8obsf3s"
  - "ducholmes-vietnam-national-university-hanoi/MNIST-SOTA/u3tn59yu"